### ISSUE TITLE
AttributeError: 'CellData' object has no attribute '_map'

### ISSUE THREAD

**Issue by balciseri** [LuaxY/PyDofus#1]
Hello out of 11460 .dlm files i was able to unpack into only 11393 .json files.
67 files failed with this error: 
File "C:\PyDofus\test\pydofus\dlm.py", line 379, in read
    self._map.topArrowCell.append(self.cellId)
AttributeError: 'CellData' object has no attribute '_map'

These are some of the failing files:108004870.dlm 108928780.dlm, 113508865.dlm. ecc.
All from the latest dofus version.

Here a screenshot: http://puu.sh/nAS86/3e3ef239ce.png

By the way can you explain me when and for what are used in dofus ?  self.topArrowCell = [], self.bottomArrowCell = [],     self.leftArrowCell = [],       self.rightArrowCell = []
Thank you!

**Comment by LuaxY** [comment]
Can you upload one of DLM file please ?
ArrowCell is used for transition between map (the orange arrow)

**Comment by balciseri** [comment]
Thank you, i was wondering why only so few maps have those arrows!
[108004870.zip](https://github.com/LuaxY/PyDofus/files/166946/108004870.zip)
[113508865.zip](https://github.com/LuaxY/PyDofus/files/166949/113508865.zip)
[108928780.zip](https://github.com/LuaxY/PyDofus/files/166950/108928780.zip)

**Comment by LuaxY** [comment]
Sorry for late reply, I have fixed the bug ;)

**Comment by balciseri** [comment]
Awesome!
