### ISSUE TITLE
Elements

### ISSUE THREAD

**Issue by TheEndGuy** [LuaxY/PyDofus#6]
O unpack do elements.ele ainda funciona ? ( versão 2.35 )

Está dando erro:
    file = sys.argv[1]
IndexError: list index out of range

**Comment by leonardo-spy** [comment]
não é por nada mas acho que ele não entende portugues

**Comment by LuaxY** [comment]
```
$ python ele_unpack.py {your elements.ele}
# file output: elements.json
```

**Comment by TheEndGuy** [comment]
$ python ele_unpack.py {elements.ele}

  # file output: elements.json

" Invalid Syntax"  .. im trying to compile in the python itself, righ t?

**Comment by LuaxY** [comment]
Show me console screenshot ;)

**Comment by TheEndGuy** [comment]
http://imgur.com/a/hCNO4

**Comment by balciseri** [comment]
Don't edit the source code, try like this: ![Screen](http://puu.sh/pOB1l/c0763c26d7.png)

**Comment by TheEndGuy** [comment]
i put the code without editing and tried the command by the shell but is again giving error.. and I put in the same folder elements.ele 

see:  http://imgur.com/a/Utihj

**Comment by LuaxY** [comment]
Use windows prompt.

`C:\Python35\python.exe C:\Users\Isaki\Desktop\PyDofus-master\ele_unpacker.py elements.ele`
(adapt if necessary)

**Comment by TheEndGuy** [comment]
Thanks man :) work !
